### ISSUE TITLE
最下面 rpath 中的 p单词小写了，应该大写

### ISSUE THREAD

**Issue by tedburner** [accforgit/DayLearnNote#2]
const isWin = path.sep.indexOf('\\') !== -1
let relativePath = absolutePath.map(apath => {
  // 得到相对路径
  const rPath = path.relative(__dirname, apath)
  // 不同系统平台的分隔符处理
  return isWin ? rPath.replace(/\\/g, '/') : **rpath**
})

**Comment by accforgit** [comment]
@jiang95 done
